import site from "../site.json" with { type: "json" };

const units = [
  { eyebrow: "SHOWER TRAILERS", title: "Private showers, ready for the job site.", text: "Clean, climate-controlled shower capacity for construction crews, events, renovations and emergency response.", image: "/images/catalog/shower-trailer-960.webp", alt: "Private shower stalls inside a temporary shower trailer", caption: "Private shower stalls inside a representative temporary shower trailer.", href: "/equipment-rental/shower-trailer/" },
  { eyebrow: "RESTROOM TRAILERS", title: "Comfortable restroom facilities.", text: "Dependable temporary restroom capacity for guests, staff and occupied facilities when permanent restrooms are unavailable.", image: "/images/catalog/restroom-trailers-960.webp", alt: "Clean restroom interior inside a temporary restroom trailer", caption: "Clean restroom interior from a representative temporary restroom facility.", href: "/equipment-rental/restroom-trailers/" },
  { eyebrow: "COMBINATION UNITS", title: "Shower and restroom in one plan.", text: "Coordinate washing, restroom access, hot water, servicing and delivery around the actual site and occupancy.", image: "/images/catalog/restroom-trailers-960.webp", alt: "Shower and restroom combination trailer interior reference", caption: "Representative shower and restroom combination-trailer interior; confirm the exact layout before booking.", href: "/services/shower-restroom-combination-trailers/" },
];
const industries = [
  ["CS", "Construction sites", "Keep crews clean and productive through multi-week and multi-month builds."],
  ["GM", "Government & military", "Support disaster response, public works, military and emergency-management operations."],
  ["EF", "Events & festivals", "Provide comfortable shower and restroom access for outdoor events, weddings and sporting programs."],
  ["HF", "Healthcare facilities", "Support staff hygiene during renovations, outages or emergency facility work."],
  ["EC", "Educational campuses", "Keep housing, athletics and campus operations moving during renovations or response work."],
  ["EI", "Energy & industrial", "Plan heavy-duty configurations, hot water and remote-site logistics for industrial operations."],
];
const faqs = [
  ["How much does a shower trailer rental cost?", "Pricing depends on the unit, occupancy, location, rental duration, site access, utilities and servicing plan. Share those details for a project-specific quote."],
  ["How quickly can a shower trailer be delivered?", "Delivery timing depends on availability, route, site readiness and the requested date. The rental team confirms the schedule before an agreement is finalized."],
  ["Are ADA-accessible shower trailers available?", "Accessible configurations may be available. Confirm the actual floor plan, access route, ramp and site requirements with the rental team."],
  ["Do you offer long-term shower trailer rentals?", "Yes. Discuss short-term or extended rental needs, servicing, delivery and removal timing with the project team."],
  ["Do you hold a GSA Schedule contract?", "Government buyers should confirm the current contract details and purchasing path with the rental specialist before relying on a procurement claim."],
];

export function Home() {
  return <div className="shower-home">
    <section className="shower-hero" aria-labelledby="shower-hero-title"><div className="shower-hero-panel"><span className="shower-kicker">TEMPORARY SHOWER RENTAL 123 · NATIONWIDE</span><h1 id="shower-hero-title">Temporary Shower Trailer Rental</h1><p>Efficient, portable and comfortable shower and restroom trailer rentals for events, construction sites, renovations and emergencies.</p><div className="shower-actions"><a className="button" href={`tel:${site.phoneE164}`}>Call {site.phoneDisplay}</a><a className="button secondary" href="/contact-us/">Request a quote</a></div><div className="shower-hero-facts"><span><strong>24/7</strong> live agent support</span><span><strong>50</strong> states served</span><span><strong>2–5</strong> day standard delivery*</span></div></div><figure className="shower-hero-image"><img src="/images/catalog/temporary-shower-trailers-960.webp" alt="Modern temporary shower trailer facilities with private stalls" width="960" height="640" fetchPriority="high" /><figcaption>Modern temporary shower and restroom facility reference; confirm the exact unit and ADA layout.</figcaption></figure></section>
    <section className="shower-section shower-intro" aria-labelledby="solutions-title"><div><span className="shower-kicker">SHOWER AND RESTROOM SOLUTIONS</span><h2 id="solutions-title">Clean facilities for the work that cannot pause.</h2></div><p>Professionally maintained shower and restroom trailers support construction, government projects, healthcare facilities, schools and commercial events. Confirm the available unit, utilities, access and delivery plan for your site.</p></section>
    <section className="shower-facts" aria-label="Service facts"><div><strong>24/7</strong><span>Live agent support</span></div><div><strong>50</strong><span>States served</span></div><div><strong>2–5</strong><span>Day standard delivery*</span></div><div><strong>GSA</strong><span>Verify current contract details</span></div></section>
    <section className="shower-section" aria-labelledby="industries-title"><span className="shower-kicker">INDUSTRIES WE SERVE</span><h2 id="industries-title">Commercial shower trailers built around your operation.</h2><div className="shower-industry-grid">{industries.map(([code, title, text]) => <article key={title}><span className="shower-industry-code">{code}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="shower-section shower-units" aria-labelledby="units-title"><div className="shower-section-heading"><div><span className="shower-kicker">EXPLORE THE FLEET</span><h2 id="units-title">Choose the facility mix your site needs.</h2></div><a className="text-link" href="/equipment-rental/">View all rental options ↗</a></div><div className="shower-unit-grid">{units.map((unit) => <article className="shower-unit-card" key={unit.href}><figure><img src={unit.image} alt={unit.alt} loading="lazy" width="960" height="640" /><figcaption>{unit.caption}</figcaption></figure><div><span className="shower-kicker">{unit.eyebrow}</span><h3>{unit.title}</h3><p>{unit.text}</p><a className="text-link" href={unit.href}>Explore this option ↗</a></div></article>)}</div></section>
    <section className="shower-section shower-included" aria-labelledby="included-title"><div><span className="shower-kicker">WHAT'S INCLUDED</span><h2 id="included-title">Comfort, privacy and dependable site support.</h2></div><div className="shower-included-grid"><p><strong>Climate-controlled comfort</strong> Year-round heating and air conditioning for changing conditions.</p><p><strong>Continuous hot water</strong> Commercial-grade water heaters for every shift or guest.</p><p><strong>Private, secure stalls</strong> Individual lockable shower compartments for privacy.</p><p><strong>Accessible options</strong> Confirm the actual ADA layout and access requirements for the selected unit.</p><p><strong>Safety flooring</strong> Slip-resistant floors designed for clean, safe step-in showering.</p><p><strong>Self-contained supply</strong> Review onboard water, power, drainage and servicing for remote sites.</p></div></section>
    <section className="shower-section shower-faq" aria-labelledby="faq-title"><span className="shower-kicker">FREQUENTLY ASKED QUESTIONS</span><h2 id="faq-title">Clear answers before you schedule.</h2><div className="shower-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="shower-cta" aria-labelledby="cta-title"><span className="shower-kicker">READY TO PLAN?</span><h2 id="cta-title">Need a temporary shower, restroom or bathroom trailer?</h2><p>Tell the logistics team about crew capacity, site footprint and scheduling.</p><div className="shower-actions"><a className="button" href={`tel:${site.phoneE164}`}>Call now: {site.phoneDisplay}</a><a className="button secondary" href="/contact-us/">Request a quote</a></div></section><p className="shower-disclaimer">*Delivery timing, availability, pricing and contract terms require confirmation for the actual project.</p>
  </div>;
}
